// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvUkruwigepS2dT0WjhY0xJs15lcr1u_M',
    appId: '1:95525920660:web:46a467d1578c25dd777981',
    messagingSenderId: '95525920660',
    projectId: 'kidschaupalcarpo',
    authDomain: 'kidschaupalcarpo.firebaseapp.com',
    storageBucket: 'kidschaupalcarpo.firebasestorage.app',
    measurementId: 'G-4CN7G5EWQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUjSv5iFUUVUGf6qijIkYJiPPGA8D4NCI',
    appId: '1:95525920660:android:765b3b288d8b142d777981',
    messagingSenderId: '95525920660',
    projectId: 'kidschaupalcarpo',
    storageBucket: 'kidschaupalcarpo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6QEnUw-20OixenRi1WOogzIf1u8l_KLw',
    appId: '1:95525920660:ios:e81683dcbdfb1d7f777981',
    messagingSenderId: '95525920660',
    projectId: 'kidschaupalcarpo',
    storageBucket: 'kidschaupalcarpo.firebasestorage.app',
    iosBundleId: 'com.example.kidschaupalcarpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6QEnUw-20OixenRi1WOogzIf1u8l_KLw',
    appId: '1:95525920660:ios:e81683dcbdfb1d7f777981',
    messagingSenderId: '95525920660',
    projectId: 'kidschaupalcarpo',
    storageBucket: 'kidschaupalcarpo.firebasestorage.app',
    iosBundleId: 'com.example.kidschaupalcarpool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvUkruwigepS2dT0WjhY0xJs15lcr1u_M',
    appId: '1:95525920660:web:524c5d24fe013237777981',
    messagingSenderId: '95525920660',
    projectId: 'kidschaupalcarpo',
    authDomain: 'kidschaupalcarpo.firebaseapp.com',
    storageBucket: 'kidschaupalcarpo.firebasestorage.app',
    measurementId: 'G-BQ54YHFVTZ',
  );
}
